# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reihenfolge.ui'
#
# Created: Sat Dec  6 14:26:27 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(595, 265)
        Dialog.setAutoFillBackground(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pButton0 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton0.sizePolicy().hasHeightForWidth())
        self.pButton0.setSizePolicy(sizePolicy)
        self.pButton0.setObjectName("pButton0")
        self.gridLayout_2.addWidget(self.pButton0, 0, 0, 1, 1)
        self.pButton11 = QtWidgets.QPushButton(Dialog)
        self.pButton11.setObjectName("pButton11")
        self.gridLayout_2.addWidget(self.pButton11, 2, 1, 1, 1)
        self.pButton12 = QtWidgets.QPushButton(Dialog)
        self.pButton12.setObjectName("pButton12")
        self.gridLayout_2.addWidget(self.pButton12, 2, 2, 1, 1)
        self.pButton8 = QtWidgets.QPushButton(Dialog)
        self.pButton8.setObjectName("pButton8")
        self.gridLayout_2.addWidget(self.pButton8, 1, 3, 1, 1)
        self.pButton3 = QtWidgets.QPushButton(Dialog)
        self.pButton3.setObjectName("pButton3")
        self.gridLayout_2.addWidget(self.pButton3, 0, 3, 1, 1)
        self.pButton13 = QtWidgets.QPushButton(Dialog)
        self.pButton13.setObjectName("pButton13")
        self.gridLayout_2.addWidget(self.pButton13, 2, 3, 1, 1)
        self.pButton2 = QtWidgets.QPushButton(Dialog)
        self.pButton2.setObjectName("pButton2")
        self.gridLayout_2.addWidget(self.pButton2, 0, 2, 1, 1)
        self.pButton10 = QtWidgets.QPushButton(Dialog)
        self.pButton10.setObjectName("pButton10")
        self.gridLayout_2.addWidget(self.pButton10, 2, 0, 1, 1)
        self.pButton1 = QtWidgets.QPushButton(Dialog)
        self.pButton1.setObjectName("pButton1")
        self.gridLayout_2.addWidget(self.pButton1, 0, 1, 1, 1)
        self.pButton5 = QtWidgets.QPushButton(Dialog)
        self.pButton5.setObjectName("pButton5")
        self.gridLayout_2.addWidget(self.pButton5, 1, 0, 1, 1)
        self.pButton6 = QtWidgets.QPushButton(Dialog)
        self.pButton6.setObjectName("pButton6")
        self.gridLayout_2.addWidget(self.pButton6, 1, 1, 1, 1)
        self.pButton7 = QtWidgets.QPushButton(Dialog)
        self.pButton7.setObjectName("pButton7")
        self.gridLayout_2.addWidget(self.pButton7, 1, 2, 1, 1)
        self.pButton4 = QtWidgets.QPushButton(Dialog)
        self.pButton4.setObjectName("pButton4")
        self.gridLayout_2.addWidget(self.pButton4, 0, 4, 1, 1)
        self.pButton9 = QtWidgets.QPushButton(Dialog)
        self.pButton9.setObjectName("pButton9")
        self.gridLayout_2.addWidget(self.pButton9, 1, 4, 1, 1)
        self.pButton14 = QtWidgets.QPushButton(Dialog)
        self.pButton14.setObjectName("pButton14")
        self.gridLayout_2.addWidget(self.pButton14, 2, 4, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setMidLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MyGame"))
        self.pButton0.setText(_translate("Dialog", "PushButton"))
        self.pButton11.setText(_translate("Dialog", "PushButton"))
        self.pButton12.setText(_translate("Dialog", "PushButton"))
        self.pButton8.setText(_translate("Dialog", "PushButton"))
        self.pButton3.setText(_translate("Dialog", "PushButton"))
        self.pButton13.setText(_translate("Dialog", "PushButton"))
        self.pButton2.setText(_translate("Dialog", "PushButton"))
        self.pButton10.setText(_translate("Dialog", "PushButton"))
        self.pButton1.setText(_translate("Dialog", "PushButton"))
        self.pButton5.setText(_translate("Dialog", "PushButton"))
        self.pButton6.setText(_translate("Dialog", "PushButton"))
        self.pButton7.setText(_translate("Dialog", "PushButton"))
        self.pButton4.setText(_translate("Dialog", "PushButton"))
        self.pButton9.setText(_translate("Dialog", "PushButton"))
        self.pButton14.setText(_translate("Dialog", "PushButton"))
        self.label.setText(_translate("Dialog", "Drücken Sie die Buttons in aufsteigender Richtung!"))

