# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyGame.ui'
#
# Created: Sun Dec  7 17:20:10 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(619, 229)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lSum = QtWidgets.QLabel(Form)
        self.lSum.setObjectName("lSum")
        self.gridLayout_4.addWidget(self.lSum, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.lOPen = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lOPen.sizePolicy().hasHeightForWidth())
        self.lOPen.setSizePolicy(sizePolicy)
        self.lOPen.setObjectName("lOPen")
        self.gridLayout_4.addWidget(self.lOPen, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.lCorrect = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lCorrect.sizePolicy().hasHeightForWidth())
        self.lCorrect.setSizePolicy(sizePolicy)
        self.lCorrect.setObjectName("lCorrect")
        self.gridLayout_4.addWidget(self.lCorrect, 1, 1, 1, 1)
        self.lWrong = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lWrong.sizePolicy().hasHeightForWidth())
        self.lWrong.setSizePolicy(sizePolicy)
        self.lWrong.setObjectName("lWrong")
        self.gridLayout_4.addWidget(self.lWrong, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.lGames = QtWidgets.QLabel(Form)
        self.lGames.setObjectName("lGames")
        self.gridLayout_4.addWidget(self.lGames, 4, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pButton0 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton0.sizePolicy().hasHeightForWidth())
        self.pButton0.setSizePolicy(sizePolicy)
        self.pButton0.setObjectName("pButton0")
        self.gridLayout_2.addWidget(self.pButton0, 0, 0, 1, 1)
        self.pButton11 = QtWidgets.QPushButton(Form)
        self.pButton11.setObjectName("pButton11")
        self.gridLayout_2.addWidget(self.pButton11, 2, 1, 1, 1)
        self.pButton12 = QtWidgets.QPushButton(Form)
        self.pButton12.setObjectName("pButton12")
        self.gridLayout_2.addWidget(self.pButton12, 2, 2, 1, 1)
        self.pButton8 = QtWidgets.QPushButton(Form)
        self.pButton8.setObjectName("pButton8")
        self.gridLayout_2.addWidget(self.pButton8, 1, 3, 1, 1)
        self.pButton3 = QtWidgets.QPushButton(Form)
        self.pButton3.setObjectName("pButton3")
        self.gridLayout_2.addWidget(self.pButton3, 0, 3, 1, 1)
        self.pButton13 = QtWidgets.QPushButton(Form)
        self.pButton13.setObjectName("pButton13")
        self.gridLayout_2.addWidget(self.pButton13, 2, 3, 1, 1)
        self.pButton2 = QtWidgets.QPushButton(Form)
        self.pButton2.setObjectName("pButton2")
        self.gridLayout_2.addWidget(self.pButton2, 0, 2, 1, 1)
        self.pButton10 = QtWidgets.QPushButton(Form)
        self.pButton10.setObjectName("pButton10")
        self.gridLayout_2.addWidget(self.pButton10, 2, 0, 1, 1)
        self.pButton1 = QtWidgets.QPushButton(Form)
        self.pButton1.setObjectName("pButton1")
        self.gridLayout_2.addWidget(self.pButton1, 0, 1, 1, 1)
        self.pButton5 = QtWidgets.QPushButton(Form)
        self.pButton5.setObjectName("pButton5")
        self.gridLayout_2.addWidget(self.pButton5, 1, 0, 1, 1)
        self.pButton6 = QtWidgets.QPushButton(Form)
        self.pButton6.setObjectName("pButton6")
        self.gridLayout_2.addWidget(self.pButton6, 1, 1, 1, 1)
        self.pButton7 = QtWidgets.QPushButton(Form)
        self.pButton7.setObjectName("pButton7")
        self.gridLayout_2.addWidget(self.pButton7, 1, 2, 1, 1)
        self.pButton4 = QtWidgets.QPushButton(Form)
        self.pButton4.setObjectName("pButton4")
        self.gridLayout_2.addWidget(self.pButton4, 0, 4, 1, 1)
        self.pButton9 = QtWidgets.QPushButton(Form)
        self.pButton9.setEnabled(True)
        self.pButton9.setObjectName("pButton9")
        self.gridLayout_2.addWidget(self.pButton9, 1, 4, 1, 1)
        self.pButton14 = QtWidgets.QPushButton(Form)
        self.pButton14.setObjectName("pButton14")
        self.gridLayout_2.addWidget(self.pButton14, 2, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pNew = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pNew.sizePolicy().hasHeightForWidth())
        self.pNew.setSizePolicy(sizePolicy)
        self.pNew.setObjectName("pNew")
        self.horizontalLayout_2.addWidget(self.pNew)
        self.pExit = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pExit.sizePolicy().hasHeightForWidth())
        self.pExit.setSizePolicy(sizePolicy)
        self.pExit.setObjectName("pExit")
        self.horizontalLayout_2.addWidget(self.pExit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setMidLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        self.pExit.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MyGame"))
        self.lSum.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "offen:"))
        self.label_4.setText(_translate("Form", "falsch"))
        self.label_5.setText(_translate("Form", "gesamt"))
        self.lOPen.setText(_translate("Form", "0"))
        self.label_3.setText(_translate("Form", "korrekt"))
        self.lCorrect.setText(_translate("Form", "0"))
        self.lWrong.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "Spiele"))
        self.lGames.setText(_translate("Form", "0"))
        self.pButton0.setText(_translate("Form", "PushButton"))
        self.pButton11.setText(_translate("Form", "PushButton"))
        self.pButton12.setText(_translate("Form", "PushButton"))
        self.pButton8.setText(_translate("Form", "PushButton"))
        self.pButton3.setText(_translate("Form", "PushButton"))
        self.pButton13.setText(_translate("Form", "PushButton"))
        self.pButton2.setText(_translate("Form", "PushButton"))
        self.pButton10.setText(_translate("Form", "PushButton"))
        self.pButton1.setText(_translate("Form", "PushButton"))
        self.pButton5.setText(_translate("Form", "PushButton"))
        self.pButton6.setText(_translate("Form", "PushButton"))
        self.pButton7.setText(_translate("Form", "PushButton"))
        self.pButton4.setText(_translate("Form", "PushButton"))
        self.pButton9.setText(_translate("Form", "PushButton"))
        self.pButton14.setText(_translate("Form", "PushButton"))
        self.pNew.setText(_translate("Form", "Neu"))
        self.pExit.setText(_translate("Form", "Ende"))
        self.label.setText(_translate("Form", "Drücken Sie die Buttons in aufsteigender Richtung!"))

